apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-gui-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth-gui

  template:
    metadata:
      labels:
        component: auth-gui
    spec:
      containers:
        - name: auth-gui
          image: arwedstorm/auth-gui
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_apiUrl
              # used with local k8s:
              # value: http://localhost/api
              # used with GC k8s:
              value: http://34.77.228.236/api
